# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='home', max_length=120),
            preserve_default=False,
        ),
    ]
