# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180122_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits', regex='^\\d{9,15}$')]),
        ),
    ]
