# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 00:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180123_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Postal code has only 6 digits', regex='^\\d{6}$')]),
        ),
    ]
