# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 22:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/shan/kart/static_cdn/protected_root'), upload_to=products.models.upload_product_file_location),
        ),
    ]
