# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name'),
        ('marketing', '0003_auto_20180107_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestModelMarketingPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True)),
                ('mailchimp_subscribed', models.NullBooleanField()),
                ('mailchimp_msg', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.GuestModel')),
            ],
        ),
    ]
