# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_guestmodelmarketingpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestmodelmarketingpreference',
            old_name='email',
            new_name='guest_user',
        ),
    ]
