# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default='fmoifg543', max_length=120),
            preserve_default=False,
        ),
    ]
